define(function(){
    return [
        {
            img:'1.jpg',
            price:93.80,
            title:'这个历史挺靠谱',
            num:155564,
            sale:1898
        },
        {
            img:'2.jpg',
            price:145.80,
            title:'写给儿童的中国历史',
            num:55564,
            sale:198
        },
        {
            img:'3.jpg',
            price:112.80,
            title:'历史的温度（套装3册）',
            num:6789,
            sale:98
        },
        {
            img:'4.jpg',
            price:273.80,
            title:'中国历史长卷1',
            num:235,
            sale:981
        },{
            img:'5.jpg',
            price:273.80,
            title:'世界：我们的历史',
            num:42322,
            sale:81
        },{
            img:'6.jpg',
            price:273.80,
            title:'世界：我们的历史',
            num:67,
            sale:81
        },{
            img:'7.jpg',
            price:4567.80,
            title:'世界：我们的历史',
            num:67,
            sale:81
        },{
            img:'8.jpg',
            price:46.80,
            title:'中国历史常识',
            num:3067,
            sale:8
        },
        {
            img:'1.jpg',
            price:93.80,
            title:'这个历史挺靠谱2',
            num:155564,
            sale:1898
        },
        {
            img:'4.jpg',
            price:145.80,
            title:'写给儿童的中国历史',
            num:55564,
            sale:198
        },
        {
            img:'3.jpg',
            price:112.80,
            title:'历史的温度（套装3册）',
            num:6789,
            sale:98
        },
        {
            img:'6.jpg',
            price:273.80,
            title:'中国历史长卷',
            num:235,
            sale:981
        },{
            img:'1.jpg',
            price:273.80,
            title:'世界：我们的历史3',
            num:42322,
            sale:81
        },{
            img:'6.jpg',
            price:273.80,
            title:'世界：我们的历史',
            num:67,
            sale:81
        },{
            img:'5.jpg',
            price:4567.80,
            title:'世界：我们的历史',
            num:67,
            sale:81
        },{
            img:'8.jpg',
            price:46.80,
            title:'中国历史常识',
            num:3067,
            sale:8
        },
        {
            img:'1.jpg',
            price:93.80,
            title:'这个历史挺靠谱',
            num:155564,
            sale:1898
        },
        {
            img:'2.jpg',
            price:145.80,
            title:'写给儿童的中国历史4',
            num:55564,
            sale:198
        },
        {
            img:'3.jpg',
            price:112.80,
            title:'历史的温度（套装3册）',
            num:6789,
            sale:98
        },
        {
            img:'1.jpg',
            price:2732.80,
            title:'中国历史长卷',
            num:235,
            sale:981
        },{
            img:'2.jpg',
            price:73.80,
            title:'世界：我们的历史',
            num:42322,
            sale:81
        },{
            img:'4.jpg',
            price:23.80,
            title:'世界：我们的历史',
            num:67,
            sale:81
        },{
            img:'2.jpg',
            price:86.80,
            title:'世界：我们的历史',
            num:67,
            sale:81
        },{
            img:'3.jpg',
            price:43.80,
            title:'中国历史常识',
            num:3067,
            sale:8
        },{
            img:'2.jpg',
            price:86.80,
            title:'世界：我们的历史666',
            num:67,
            sale:81
        },{
            img:'3.jpg',
            price:43.80,
            title:'中国历史常识666',
            num:3067,
            sale:8
        }
    ]
})